name: CI
on:
  push:
  schedule:
    - cron:  '0 6 * * 5' # on every Friday at 6:00
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.downgrade-compat }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '1' # latest Julia v1
            os: ubuntu-latest
            downgrade-compat: false
          - version: '1' # latest Julia v1
            os: macos-latest
            downgrade-compat: false
          - version: '1' # latest Julia v1
            os: windows-latest
            downgrade-compat: false
          - version: 'lts' # latest Julia LTS
            os: ubuntu-latest
            downgrade-compat: false
          - version: 'lts' # latest Julia LTS
            os: ubuntu-latest
            downgrade-compat: true
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-downgrade-compat@v2
        if: ${{ matrix.downgrade-compat }}
        with:
          mode: 'alldeps'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
      - uses: codecov/codecov-action@v5
        if: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
        with:
          files: lcov.info
